### ISSUE TITLE
Next month startingDateValue and endingDateValue crash.

### ISSUE THREAD

**Issue by Sebarkar** [krystalcampioni/vue-hotel-datepicker#139]
Problem, if I choice today (2019-04-16 - April, days in May - there is [Vue warn]
Error in render: "TypeError: Cannot read property 'days' of undefined"

Another month selection works well.

        <HotelDatePicker :endingDateValue="new Date (2019-05-22)"
                         :startingDateValue="new Date (2019-05-15)"
        ></HotelDatePicker>

**Comment by AdrienMoretti** [comment]
Hey, can you check your version of Vue Hotel Date Picker in your package-lock.json?
Be careful with your version of Vue Hotel Date Picker, because the version 2.7.1 doesn't work, i had the same problem as you.

To solve it, i replaced "vue-hotel-datepicker": "^2.6.4" by "vue-hotel-datepicker": "2.6.4" in package.json

Next, remove node_modules folder, package-lock.json file and install everything again :)

https://www.npmjs.com/package/vue-hotel-datepicker

**Comment by Sebarkar** [comment]
Hello, Adrien, thanks, it means that I need update newest version to old one? It's not so important, cos i have 8 month to finish job on this project, maybe there will be fix that will decide this problem in future.

Anyway thanks a lot, like a reserve way, I had taken it.
