### ISSUE TITLE
Keep a Changelog

### ISSUE THREAD

**Issue by guillaumebriday** [krystalcampioni/vue-hotel-datepicker#197]
### Description

Congrats for the 3.0 released! But as long a major version involved a breaking change, we don't know how to upgrade from 2.x to 3.x. There is no CHANGELOG.md nor informations in the releases tab.

Would you consider adding a CHANGELOG.md file or adding some information in the release section?

Maybe https://keepachangelog.com/en/1.0.0/ is a good start?

Thank you for your work 🙏

**Comment by matiasperrone** [comment]
There are not breaking changes, mainly we change the way that the software is build.
Now using the vue-service-cli.

Sure, maybe it should have a changelog, but I ran out of time right now, but, don't worries it will be addressed soon.

Any way there are no breaking changes, I am trying hard to update the documentation to the new version since it using an old version and @krystalcampioni has not time right now either.

This version is a serious update on the dependencies that were old. I am working on bring some changes made on forks that fixes bugs and adds new features.

Check the commits section for the pseudo-changelog.
