### ISSUE TITLE
[4.x] .datepicker__month-day--last-day-selected CSS isn't consistent with .datepicker__month-day--selected

### ISSUE THREAD

**Issue by mariusa** [krystalcampioni/vue-hotel-datepicker#226]
These 2 use `background: HEX`
```
.datepicker__month-day--first-day-selected,
.datepicker__month-day--last-day-selected {
    background: ...;
}
```

but this uses `background-color: RGB`
```
.datepicker__month-day--selected {
    background-color: ...;
}
```

Please use only 1 way, to be consistent.

* background-color vs background
* HEX vs RGB

Hex codes can have opacity too: https://alligator.io/css/hex-code-colors-alpha-values/#:~:text=Comparing%20Hex%20Code%2BAlpha%20Format%20to%20RGBA&text=255%2C%20256).,opaque%20the%20color%20will%20be.

**Comment by superbiche** [comment]
I'm doing a full rewrite of the Sass code to : 

1. Make most of the values bound to variables  
2. Extract the variables in a separate file with `!default` values, so one can easily define his own vars *before* including the stylesheet in order to customize the appearance. 

This should land this weekend or the next one. Big delivery for a client this week so I'm pretty busy.

**Comment by matiasperrone** [comment]
@superbiche with your CSS we will launch the official v4 production release.

**Comment by superbiche** [comment]
This will be shipped this weekend :+1:

**Comment by superbiche** [comment]
Fixed in #230 - PR is still a draft but this one is OK

**Comment by matiasperrone** [comment]
@mariusa I think it will help you too.

**Comment by matiasperrone** [comment]
merged!
