### ISSUE TITLE
disabledDates not disabled when used with disabledDaysOfWeek

### ISSUE THREAD

**Issue by Maxximus007** [krystalcampioni/vue-hotel-datepicker#29]
Hi,

Perhaps an edge case, but I have the following datepicker:
`          <date-picker
            DatePickerID="calendar"
            :format="'DD-MM-YYYY'"
            :disabledDaysOfWeek="['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Sunday']"
            :disabledDates="['2017-11-11', '2017-11-12', '2017-11-13', '2017-11-14', '2017-11-15', '2017-11-16', '2017-11-17', '2017-11-18', ]"
            :enableCheckout="true"
            :allowedRanges="[7,14,21]"
            :minNights="7"
            :showCloseButton="true"
          ></date-picker>
`
In this case only Saturday is selectable as Check-in and a range of 7, 14, 21 days (eg. Check-out on Saturday again).
Here a week is blocked (disabledDates). But after selecting 4-11 as Check-in (one week before the disabledDates), the datepicker allows to select 18-11 as check-out, while this includes disabled dates.

Hope you're able to take a look at it!

**Comment by Maxximus007** [comment]
FYI: In version 1.x it worked as expected.

**Comment by krystalcampioni** [comment]
@Maxximus007 v.2 was a full rewrite of v1. We removed lots of features and introduced others. The way that the enableCheckout works also changed on v2 to make it easier to understand and maintain. I'll take a look at it to see what's not working correctly. If you manage to understand what the problem is, meanwhile, and would like to contribute, feel free to submit a pull request :)

**Comment by matiasperrone** [comment]
Solved in v4.0.0-beta.2
