### ISSUE TITLE
Maintainers Wanted

### ISSUE THREAD

**Issue by krystalcampioni** [krystalcampioni/vue-hotel-datepicker#67]
Unfortunately, I haven't had much free time to maintain this project 😢 
If you find this package useful and would like to help maintain it or collaborate, let me know in this issue 🖖🏽

**Comment by amulchinock** [comment]
Happy to help!

**Comment by matiasperrone** [comment]
I am in!

**Comment by joffreyBerrier** [comment]
Hi I have created a fork of the repo and i have do some changes

- https://github.com/joffreyBerrier/vue-hotel-datepicker/projects/1
- https://github.com/joffreyBerrier/vue-hotel-datepicker

**Comment by cjlaborde** [comment]
> Hi I have created a fork of the repo and i have do some changes
> 
> * https://github.com/joffreyBerrier/vue-hotel-datepicker/projects/1
> * https://github.com/joffreyBerrier/vue-hotel-datepicker

I didn't like that you removed the original design, it doesn't look good now, 
I preferred the green look since it matched my project color theme.
As well why the issue tab not available in your fork? 
I had to uninstall your fork because of this, is too bad because I liked a lot of changes you did.

**Comment by matiasperrone** [comment]
All these changes are available in v3 did you try it?

**Comment by cjlaborde** [comment]
> All these changes are available in v3 did you try it?

Does v3 has these features that Joffrey implemented?
Use vue-cli
Remove the pug html, use html
Remove some useless dependencies
Rewrite code
Add eslint airbnb + prettier
Remove useless condition like empty if or else
Add return for all computed
Add a bind key on v-for
Rewrite jest test
Remove v-html / v-text use {{ }}
Add emit when clearSelection
Remove querySelector, use refs
Fix bug: impossible to open the calendar when clearselection is trigger
Allows to have half a day, if you have check in at noon and checkout before noon

Notice that v3 still uses pug instead of HTML
As well does it has separated css you can access like this?
import 'vue-hotel-datepicker2/dist/vueHotelDatepicker2.css';

**Comment by matiasperrone** [comment]
@joffreyBerrier and @cjlaborde  please continue in #192

**Comment by matiasperrone** [comment]
@superbiche you are a Collaborator now!

**Comment by matiasperrone** [comment]
welcome @superbiche !
