### ISSUE TITLE
Cannot select next checkout date when it is disabled

### ISSUE THREAD

**Issue by hoangnguyen291** [krystalcampioni/vue-hotel-datepicker#69]
### Description

ex: If tomorrow is booked by someone else, I can't select checkin date on today and checkout on tomorrow. In fact, tomorrow should be enabled if I selected checkin today. 

### Steps to Reproduce

1. Disable 2018-04-25
2. Select checkin 2018-04-24 
3. 2018-04-25 should be enabled for checkout.

**Comment by hoangnguyen291** [comment]
Currently I have fixed this problem by modify Day.vue disableNextDays()

`  disableNextDays(){
      if ( !this.isDateLessOrEquals(this.date, this.nextDisabledDate)
            && this.nextDisabledDate !== Infinity) {
              this.isDisabled = true;
      }
      else if ( this.isDateLessOrEquals(this.date, this.checkIn) ) {
        this.isDisabled = true;
      }
      if ( this.compareDay(this.date, this.checkIn) == 0 && this.options.minNights == 0) {
        this.isDisabled = false;
      }
      if (this.isDateLessOrEquals(this.checkIn, this.date) && this.options.enableCheckout ){
          this.isDisabled = false;
      }
      else {
          let enableDate = this.sortedDisabledDates.find(p => p > this.checkIn);
          let lastDisableDate = this.sortedDisabledDates.find(p => p < this.date && p > this.checkIn);
          if (this.compareDay(this.date, this.checkIn) == 1 && this.compareDay(this.date, enableDate)==0) {
              this.isDisabled = false;
          }
          if (lastDisableDate) {
              this.isDisabled = true;
          }
          return
      }
    },`

**Comment by amulchinock** [comment]
@hoangnguyen291 Are you suggesting that we allow checkin/checkout on the same date?

For example- your "hotel" has a check out at 10am on 01/01/1970, and another guest wishes to check in at 3pm on 01/01/1970.

At the moment, the datepicker doesn't specify date/times for the threshold of date cutoff. This means, if you block out a date as disabled (due to an existing booking), then there is no way for the user to check in on that date.

Feel free to make a pull request based on your code.

@krystalcampioni feature request? :)

**Comment by matiasperrone** [comment]
Merged with #74
